### ISSUE TITLE
Fail to run as a service on openhabian  (runs OK when started manually)

### ISSUE THREAD

**Issue by cavamora** [fbacker/broadlink-mqtt-bridge#16]
May 12 11:39:55 openHABianPi systemd[1]: Starting Broadlink MQTT Bridge...
May 12 11:39:55 openHABianPi systemd[1]: Started Broadlink MQTT Bridge.
May 12 11:39:55 openHABianPi node[4037]: /srv/openhab2-conf/broadlink-mqtt-bridge/index.js:63
May 12 11:39:55 openHABianPi node[4037]: const { timestamp, level, message, ...args } = info;
May 12 11:39:55 openHABianPi node[4037]: ^^^
May 12 11:39:55 openHABianPi node[4037]: SyntaxError: Unexpected token ...
May 12 11:39:55 openHABianPi node[4037]: at createScript (vm.js:53:10)
May 12 11:39:55 openHABianPi node[4037]: at Object.runInThisContext (vm.js:95:10)
May 12 11:39:55 openHABianPi node[4037]: at Module._compile (module.js:543:28)
May 12 11:39:55 openHABianPi node[4037]: at Object.Module._extensions..js (module.js:580:10)
May 12 11:39:55 openHABianPi node[4037]: at Module.load (module.js:488:32)
May 12 11:39:55 openHABianPi node[4037]: at tryModuleLoad (module.js:447:12)
May 12 11:39:55 openHABianPi node[4037]: at Function.Module._load (module.js:439:3)
May 12 11:39:55 openHABianPi node[4037]: at Module.runMain (module.js:605:10)
May 12 11:39:55 openHABianPi node[4037]: at run (bootstrap_node.js:427:7)
May 12 11:39:55 openHABianPi node[4037]: at startup (bootstrap_node.js:151:9)
May 12 11:39:55 openHABianPi systemd[1]: broadlinkbridge.service: main process exited, code=exited, status=1/FAILURE
May 12 11:39:55 openHABianPi systemd[1]: Unit broadlinkbridge.service entered failed state.

**Comment by cavamora** [comment]
node version is different from /usr/bin and running just ./node
