### ISSUE TITLE
Record IR do not work for electra AC remote

### ISSUE THREAD

**Issue by smartnakh** [fbacker/broadlink-mqtt-bridge#2]
2018-10-11 13:50:12 [info]:     Web User want action {
  "action": "recordir",
  "topic": "broadlink2/broadlink/tv/samsung/power222"
}
2018-10-11 13:50:12 [debug]:    prepareAction {
  "action": "recordir",
  "topic": "broadlink2/broadlink/tv/samsung/power222",
  "origin": "web"
}
2018-10-11 13:50:12 [debug]:    deviceEnterLearningIR
2018-10-11 13:50:12 [info]:     recordIR: Press an IR signal
2018-10-11 13:50:13 [info]:     recordIR: Timeout in 30
2018-10-11 13:50:14 [info]:     recordIR: Timeout in 29
2018-10-11 13:50:15 [info]:     recordIR: Timeout in 28
2018-10-11 13:50:16 [info]:     recordIR: Timeout in 27
2018-10-11 13:50:16 [debug]:    Broadlink IR RAW
/etc/openhab2/scripts/broadlink-mqtt-bridge/index.js:460
      device.emitter.off("rawData", callback);
                     ^

TypeError: device.emitter.off is not a function
    at Device.callback (/etc/openhab2/scripts/broadlink-mqtt-bridge/index.js:460:22)
    at emitOne (events.js:116:13)
    at Device.emit (events.js:211:7)
    at Device.onPayloadReceived (/etc/openhab2/scripts/broadlink-mqtt-bridge/node_modules/broadlinkjs-rm/index.js:389:14)
    at Socket.socket.on (/etc/openhab2/scripts/broadlink-mqtt-bridge/node_modules/broadlinkjs-rm/index.js:274:14)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)

**Comment by fbacker** [comment]
do you know if it has found the broadlink device?

like this:
https://user-images.githubusercontent.com/31652547/46808151-5160d100-cd74-11e8-8e38-791c7761f6f1.png

**Comment by fbacker** [comment]
@smartnakh 
please run ```git pull``` in the folder to try out latest version. 
In the webgui make sure a broadlink device exist. You can try the 'devices' list to force a print of connected devices.
