### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by tgamlieli** [fbacker/broadlink-mqtt-bridge#31]
After upgrade to the latest commit . i can't start the service.
remove /srv/openhab2-conf/broadlink-mqtt-bridge directory and try to install from scratch
but it not fix the issue.

`npm run production

> broadlink-mqtt-bridge@1.0.0 production /srv/openhab2-conf/broadlink-mqtt-bridge
> node -r esm index.js

LOGLEVEL: debug
2019-12-20 07:44:24 [debug]:    MQTT Options
{
  "host": "127.0.0.1",
  "port": 1883,
  "protocol": "mqtt",
  "subscribeBasePath": "broadlink/",
  "defaultProtocol": "mqtt",
  "keepalive": 60,
  "reschedulePings": true,
  "protocolId": "MQTT",
  "protocolVersion": 4,
  "reconnectPeriod": 1000,
  "connectTimeout": 30000,
  "clean": true,
  "resubscribe": true,
  "clientId": "mqttjs_aaf684d0",
  "hostname": "127.0.0.1"
}
2019-12-20 07:44:25 [info]:     Starting Broadlink MQTT NodeJS Application
2019-12-20 07:44:25 [debug]:    GUI Web listen on port 3000
2019-12-20 07:44:25 [debug]:    MQTT Connected, subscribe: broadlink/#
2019-12-20 07:44:25 [info]:     Device found model: Broadlink RM Mini, id: 34ea34cdf7b6, ip: 192.168.1.62
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Printf.require.format.combine.format.printf [as template] (/srv/openhab2-conf/broadlink-mqtt-bridge/src/logger.js:27:44)
    at Printf.transform (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/logform/printf.js:11:26)
    at Format.info [as transform] (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/lib/winston/logger.js:305:29)
    at DerivedLogger.Transform._read (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at DerivedLogger.Writable.write (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:303:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! broadlink-mqtt-bridge@1.0.0 production: `node -r esm index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the broadlink-mqtt-bridge@1.0.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/openhabian/.npm/_logs/2019-12-20T07_44_25_342Z-debug.log
`

**Comment by Majestry** [comment]
I have similar issue when device is found. Here is the log from syslog:
Dec 21 12:33:27 openHABianPi npm[1874]: 2019-12-21 11:33:27 [#033[32minfo#033[39m]: #011Device found model: Broadlink RM Mini, id: 24dfa742f32b, ip: 192.168.0.21
Dec 21 12:33:27 openHABianPi npm[1874]: TypeError: Converting circular structure to JSON
Dec 21 12:33:27 openHABianPi npm[1874]:     at JSON.stringify (<anonymous>)
Dec 21 12:33:27 openHABianPi npm[1874]:     at Printf.require.format.combine.format.printf [as template] (/srv/openhab2-conf/broadlink-mqtt-bridge/src/logger.js:27:44)
Dec 21 12:33:27 openHABianPi npm[1874]:     at Printf.transform (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/logform/printf.js:11:26)
Dec 21 12:33:27 openHABianPi npm[1874]:     at Format.info [as transform] (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/logform/combine.js:20:24)
Dec 21 12:33:27 openHABianPi npm[1874]:     at DerivedLogger._transform (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/lib/winston/logger.js:305:29)
Dec 21 12:33:27 openHABianPi npm[1874]:     at DerivedLogger.Transform._read (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
Dec 21 12:33:27 openHABianPi npm[1874]:     at DerivedLogger.Transform._write (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
Dec 21 12:33:27 openHABianPi npm[1874]:     at doWrite (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:405:139)
Dec 21 12:33:27 openHABianPi npm[1874]:     at writeOrBuffer (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:394:5)
Dec 21 12:33:27 openHABianPi npm[1874]:     at DerivedLogger.Writable.write (/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:303:11)
Dec 21 12:33:27 openHABianPi npm[1874]: npm ERR! code ELIFECYCLE
Dec 21 12:33:27 openHABianPi npm[1874]: npm ERR! errno 1
Dec 21 12:33:27 openHABianPi npm[1874]: npm ERR! broadlink-mqtt-bridge@1.0.0 production: `node -r esm index.js`
Dec 21 12:33:27 openHABianPi npm[1874]: npm ERR! Exit status 1
Dec 21 12:33:27 openHABianPi npm[1874]: npm ERR!

After reverting changes from this commit: https://github.com/fbacker/broadlink-mqtt-bridge/commit/76c146890ca09b0349c2bb4705de2de0d9ec33bd#diff-1e9c3d615e9ebaaaa3669b4c2fd87d00
works again

**Comment by fbacker** [comment]
Guessing that it crashes when running Log level DEBUG and it should print detailed broadlink device info. It's fixed in latest release. Please update and try it.

```bash -c "$(curl -sL https://raw.githubusercontent.com/fbacker/broadlink-mqtt-bridge/master/installers/raspberry.sh)"```

**Comment by xandcapcom** [comment]
I have the same problem, everything updated but does not work, the web interface of the log on port 3001 runs, but Interface 3000 does not run. I'm using the 'Buster' dist can this be?
