### ISSUE TITLE
NODE_ENV value of 'production' did not match any deployment config file names.

### ISSUE THREAD

**Issue by miguc** [fbacker/broadlink-mqtt-bridge#46]
Hello I just installed the broadlink-mqtt-bridge, but the service doesn't start.

I saw in the service status this message:

    sudo service broadlinkbridge status -l
    ● broadlinkbridge.service - Broadlink MQTT Bridge
       Loaded: loaded (/etc/systemd/system/broadlinkbridge.service; disabled)
       Active: active (running) since jue 2020-07-02 21:21:06 CEST; 11s ago
     Main PID: 31187 (npm)
       CGroup: /system.slice/broadlinkbridge.service
               ├─31187 npm
               ├─31201 sh -c node -r esm index.js
               └─31202 node -r esm index.js

    jul 02 21:21:06 PI_314 systemd[1]: Stopping Broadlink MQTT Bridge...
    jul 02 21:21:06 PI_314 systemd[1]: Starting Broadlink MQTT Bridge...
    jul 02 21:21:06 PI_314 systemd[1]: Started Broadlink MQTT Bridge.
    jul 02 21:21:09 PI_314 npm[31187]: > broadlink-mqtt-bridge@1.0.0 production /srv/openhab2-conf/broadlink-mqtt-bridge
    jul 02 21:21:09 PI_314 npm[31187]: > node -r esm index.js
    jul 02 21:21:15 PI_314 npm[31187]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
    jul 02 21:21:15 PI_314 npm[31187]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
    jul 02 21:21:15 PI_314 npm[31187]: LOGLEVEL: debug

I saw the wiki with the strict mode and I didn't find what the problem is.

I saw syslog and and it takes me to npm logs.

The npm log, which is repeating three times per minute, includes the next content:

    cat 2020-07-02T19_26_40_646Z-debug.log
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'production' ]
    2 info using npm@6.14.4 
    3 info using node@v10.21.0 
    4 verbose run-script [ 'preproduction', 'production', 'postproduction' ] 
    5 info lifecycle broadlink-mqtt-bridge@1.0.0~preproduction: broadlink-mqtt-bridge@1.0.0 
    6 info lifecycle broadlink-mqtt-bridge@1.0.0~production: broadlink-mqtt-bridge@1.0.0 
    7 verbose lifecycle broadlink-mqtt-bridge@1.0.0~production: unsafe-perm in lifecycle true 
    8 verbose lifecycle broadlink-mqtt-bridge@1.0.0~production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/openhab2-conf/broadlink-mqtt-bridge/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
    9 verbose lifecycle broadlink-mqtt-bridge@1.0.0~production: CWD: /srv/openhab2-conf/broadlink-mqtt-bridge 
    10 silly lifecycle broadlink-mqtt-bridge@1.0.0~production: Args: [ '-c', 'node -r esm index.js' ] 
    11 silly lifecycle broadlink-mqtt-bridge@1.0.0~production: Returned: code: 1  signal: null 
    12 info lifecycle broadlink-mqtt-bridge@1.0.0~production: Failed to exec production script 
    13 verbose stack Error: broadlink-mqtt-bridge@1.0.0 production: `node -r esm index.js` 
    13 verbose stack Exit status 1 
    13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16) 
    13 verbose stack     at EventEmitter.emit (events.js:198:13) 
    13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14) 
    13 verbose stack     at ChildProcess.emit (events.js:198:13) 
    13 verbose stack     at maybeClose (internal/child_process.js:982:16) 
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) 
    14 verbose pkgid broadlink-mqtt-bridge@1.0.0 
    15 verbose cwd /srv/openhab2-conf/broadlink-mqtt-bridge 
    16 verbose Linux 4.9.35-v7+ 
    17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production" 
    18 verbose node v10.21.0 
    19 verbose npm  v6.14.4 
    20 error code ELIFECYCLE 
    21 error errno 1 
    22 error broadlink-mqtt-bridge@1.0.0 production: `node -r esm index.js` 
    22 error Exit status 1 
    23 error Failed at the broadlink-mqtt-bridge@1.0.0 production script. 
    23 error This is probably not a problem with npm. There is likely additional logging output above. 
    24 verbose exit [ 1, true ] 

I'm running openhab2 and mosquitto in a RPI 3b+.

Thanks for your attention.

**Comment by miguc** [comment]
The origin of the problem is the same one from the issue #44 .  I'll close this issue and I will continue investigating and writing in it.
