### ISSUE TITLE
unable to access GUI after update

### ISSUE THREAD

**Issue by gargamelonly** [fbacker/broadlink-mqtt-bridge#54]
I have updated to latest version, reinstalled over existing installation.
Running openHAB. The port 3000 is occupied by Grafana.
Kept the same local.json config as before with port 3030 assigned to GUI.
I am able to see the logs in port 3001, identifying the device and existing commands.
Commands are sent and run ok. Still the GUI on port 3030 is not accessible. 
It worked ok before the update.

**Comment by gargamelonly** [comment]
It looks like the webserver does not even start.
Please help resolve this issue.

**Comment by gargamelonly** [comment]
```
[10:45:18] openhabian@openHABianPi:~/broadlink-mqtt-bridge$ node index.js
/home/openhabian/broadlink-mqtt-bridge/index.js:1
import { exec } from 'child_process';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by gargamelonly** [comment]
Also does not work on a clean install.

**Comment by miguelbueno** [comment]
Same here. In a brand new install on Rasp4

**Comment by melkati** [comment]
Same thing here on Rasp3

**Comment by fbacker** [comment]
Might be because the 'new' autoinstaller doesn't install in the old path. You would need to goto the folder ```cd /srv/openhab2-conf/``` before running the auto installer.

https://github.com/fbacker/broadlink-mqtt-bridge/wiki/Installation

I've no real release cycles of good way of making 'major' releases :(  hopefully this will solve the issue. I'm planning of making better docker releases and then removing this auto installer in the future.

**Comment by mtzro2003** [comment]
I had the same problem... GUI not responding on port 3000.
I noticed in the log that the GUI is
```
Listen on ip 127.0.0.1
```
So, I modified the `src/web.js` changing
```
class WebserverClass {
  constructor() {
    this.host = isDocker() ? '0.0.0.0' : '127.0.0.1';
    logger.info(`Listen on ip ${this.host}`);
```
to
```
class WebserverClass {
  constructor() {
    this.host = '0.0.0.0';
    logger.info(`Listen on ip ${this.host}`);
```

**Comment by gargamelonly** [comment]
> 
> 
> I had the same problem... GUI not responding on port 3000.
> I noticed in the log that the GUI is
> 
> ```
> Listen on ip 127.0.0.1
> ```
> 
> So, I modified the `src/web.js` changing
> 
> ```
> class WebserverClass {
>   constructor() {
>     this.host = isDocker() ? '0.0.0.0' : '127.0.0.1';
>     logger.info(`Listen on ip ${this.host}`);
> ```
> 
> to
> 
> ```
> class WebserverClass {
>   constructor() {
>     this.host = '0.0.0.0';
>     logger.info(`Listen on ip ${this.host}`);
> ```

Does not resolve the issue for me.

**Comment by Astral0** [comment]
The problem is localised in commit cabd581072247b03dee2fee9ebda53aba4d5ebc4

And the solution is to revert the line 302 of file  src/web.js to its previous state : 

  this.server.listen(config.settings.gui.port, this.host, () => {

replace by : 
  this.server.listen(config.settings.gui.port, () => {

Regard

**Comment by gargamelonly** [comment]
> 
> 
> The problem is localised in commit [cabd581](https://github.com/fbacker/broadlink-mqtt-bridge/commit/cabd581072247b03dee2fee9ebda53aba4d5ebc4)
> 
> And the solution is to revert the line 302 of file src/web.js to its previous state :
> 
> this.server.listen(config.settings.gui.port, this.host, () => {
> 
> replace by :
> this.server.listen(config.settings.gui.port, () => {
> 
> Regard

That is correct. 
I modified the file and now it works.

**Comment by gargamelonly** [comment]
Please help...
Upgraded to an RPI4 and did a new auto install.
Now nothing is working again. Throwing different errors in index.js, service crash, does not start.
Latest Bullseye OS installed. 
NPM version 7.5.2
Node version v12.22.5
